title: Kristin Chang # your name (or website title) here
logo: "images/profpic3.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduate Student at University of Pennsylvania
  <br><br>
  Dual Masters of City Planning and Urban Spatial Analytics, Expected Graduation: December 2022
  <br><br>
  <a href="https://www.linkedin.com/in/kristin-chang-upenn2022/">View My LinkedIn Profile</a> 
  <br><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
